import React from "react";
import '../../App.css';
export default function History(){
    return(
        <>
        <img src="./images/newdurga.jpg" alt="" className="page-img"></img>
            <h1 className="page_heading">History</h1>
            <p className="page-info">The temple of  Kanaka Durga the Goddess of power, riches and benevolence and the presiding deity of Vijayawada, is thronged by lakhs of pilgrims for worship during the “Navarathri” festival which is celebrated with Religious fervor, pomp and festivity. The ancient temple of Kanaka Durga , a top the Indrakeeladri hill on the banks of the Sacred river Krishna in Vijayawada, abounds with legends of historical interest.

Indrakeeladri is unique in that it has been the chosen abode of Kanaka Durga and Malleswara as Swayambhu (the self-existent one). Here Durga is on the right side of Malleswara as against the tradition of Goddesses taking their position on the left of their consorts. This shows that Shakthi is predominant on the Indrakeeladri.</p>
<br/>
<h1 className="page_heading">Specialties of Indrakeeladri Kanakadurga</h1>
<p className="page-info">Goddess is looking towards north-east with cool smile and bliss. Because of which the devotees are blessed with whatever they pray for.
This is only temple in the world where the main diety (moola varlu) are decorated in forms of Sri Saraswati, Sri Maha Lakshmi, Sri Bala Tripura Sundari, Sri Rajarajeswari, Sri Mahishasura mardini, Sri Durga devi, Sri Annapurna devi, Sri Gayatri, Sri Lalitha Tripura Sundari</p>
<br/>
<h1 className="page_heading">Story</h1>
<p className="page-info">In good olden days a Yaksha named ‘KEELA’ had been performing severe penance upon goddess Durga. Goddess Durga was pleased by his penance and appeared before him. She asked him to beg a boon. Keela was so happy by the words of Goddess Durga and begged like this, “O holy Mother! you should always be in my heart. This is the one and only my desire”. Listened goddess Durga and gave the boon with showering the lunar lights of smile and said, “My Son! You remain here at this holiest planes of river Krishna in the form of mountain. In Krithayuga, after the assassination of demons, I will remain in your heart”.</p>
<br/>
<p className="page-info">
As such, by the order of goddess Durga, Keela had been waiting in the form of mountain for goddess Durga. After sometime, in the Krithayuga goddess Durga killed Mahishasura who was a disaster for World. Then goddess Durga shined on the Keela mountain with eight arms in the form of MAHISHASURA MARDINI as she had given boon to keela. On this mountain, goddess Durga had been glowing with the lighting of crores of suns, with golden colour. Since that, Indra and all the deities praised her chanting “KANAKA DURGA” and they had been worshipping her daily. This mountain has attained the name “INDRAKEELADRI” from those times, since all the deities are visiting this mountain. Likewise, since goddess Durga shined on this mountain with golden colour glowing, the name ‘KANAKACHALA’ also attained by this mountain. Holy Indrakeeladri mountain became holiest after prevailing goddess Durga on this. Then Brahma Deva had a sacred intution that Lord Siva also should prevail on this mountain. For this holy purpose, he had performed ‘Sata Aswamedha Yaga’. By this, lord Maheswara pleased with his devotion and rested in the form of ‘Jyothirlinga’ on this mountain. By the first time, Brama Deva worshipped lord Siva with Jasmine flowers (Mallika) with great devotion.</p><br/>
<p className="page-info">Since Lord Siva was worshipped with Jasmine flowers by Brahma Deva, he has attained the name. ‘MALLIKESA’. After this, in Dwaparayuga Arjuna, middle one of the Pandavas, awfully penanced about Parameswara, seeking ‘Pasupatastra’. Parameswara wanted to test Arjuna and fought with him. Finally Lord Siva got pleased with the devotion and dauntlessness of Arjuna and offered him Pasupatastra. From that day ‘MALLIKESA’had attained the name ‘MALLIKESWARA’ since he faught with Arjuna with greatest bravery. Days were passing on and on. In Kaliyuga, Jagadguru Sri Adi Sankaracharya observed that the Malleswara Jyothirlinga was in bad invisible condition and he re¬installed Malleswara Swamy at the Northern Part to the temple of Goddess Durga. From that day onwards, Malleswara Swamy also has been worshiping by all the devotees. Since goddess Durga has been prevailing at the Southern direction to Lord Malleswara, this Indrakeeladri renowned in the World as power prominent centre the “KANAKA DURGA KSHETRA”.</p><br/>
<p className="page-info">When Indrakeeladri came in the way of the River Krishna the Gods requested the hill to allow the river to pass through it to join the sea. Keeludu obliged and gave a small passage for the river. But the ferocious Krishna made the passage larger than permitted and carried a part of the hill four miles downstream to Yanamalakuduru, where there is now a hillrock called “Thelukonda” or floating hillrock. According to another legend, Kanaka Durga borrowed the nose-stud of the Krishna and to avoid returning it jumped up the hill. Krishna vowed to take back her ornament by raising her level to the hill top by the end of kaliyuga.<br/>Adi-Sankaracharya visited the temple and installed the Srichakra and initiated workship of Kanaka Durga in vedic ways, and avoided animal sacrifice<br/></p>
<br/><p className="page-info">Vijayawada is known in mythology as Vijayavata, and is mentioned in some inscriptions as Rajendracholapura also. it is a famous place of pilgrimage on the river Krishna, and ‘has a temple dedicated to Lord Siva in his aspect of Malleswara or Jayasena. Sage Agasthya is said to have been the greatest devotee of this deity and admirer of the deity’s several leelas.The origin or installation of Kanaka – durga Devi at Vijayawada is unknown. She is said to be Swayambu or selfmanifest. She also takes the aspect of Chandi or destroyer of the demon Durgama who was causing havoc among the peace – loving inhabitants of Dakshinapatha.

One of these hills is called Indrakila, which is a famous hill mentioned in the Mahabharata as the place where the Pandava hero Arjuna obtained from Lord Siva an important weapon called Pasupatastra. The aspect of Lord Siva who appeared before Arjuna for granting him the boon is Kirata or the hunter. Bharavi in his celebrated Kavya “The Kirtarjuneeya” has immortalized this. The temple of Vijayeswara is attributed to Arjuna to commemorate the event of obtaining Pasupatha. The shrine has the representation of this and many other events of the Mahabharata depicated in sculpture form.</p>
<h1 className="page_heading">The legend is as follows</h1><br/>
<p className="page-info">During their Arsnyavaas, the Pancha Pandavas came to Darukavana, where Vedavyasa met them, and told them that one of them should perform Tapascharya in praise of Lord Siva, and obtain from him, the Pasupatastra as a boon, so that they may easily conquer their enemies. Arjuna was chosen for this task and he betook himself to the top of the Indrakila hill (which is said to be the same as the Indrakila hill of Vijayawada) and was performing intense Tapascharya, with his arms upraised, and standing on one foot, and surrounded by the Pancha Agnis or five fires, with four artificial fires around him, and the fifth being the Sun God himself above him. Being pleased with the great Tapascharya of Arjuna, Lord Siva wanted to further test his sincerity, before granting him the desired boon, and therefore took the form of a Kirata or hunter. Parvati also dressed herself as a huntress and the Sivagana of the Lord also came in several disguises. Accompanied by all these, Lord Siva was hunting on the Indrakila bill, driving a wild boar in front of him.</p>
     
       
        </>

    )
}